services:
  - type: web
    name: formi-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn formi_backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: formi_backend.settings
